.TH recipe-manuals 7 "Honey Garlic Tofu" "" "Honey Garlic Tofu"

.SH NAME
Honey Garlic Tofu

.SH INGREDIENTS
.IP \[bu]
Extra Firm Tofu (454g, 1 lb.)
.IP \[bu]
Vegetable Oil (15mL, 1 tablespoon)
.IP \[bu]
Soy Sauce (45mL, 3 tablespoons)
.IP \[bu]
Sesame Oil (15mL, 1 tablespoon)
.IP \[bu]
Rice Vinegar (10mL, 2 teaspoons)
.IP \[bu]
Red Pepper Flakes (0.625mL, 1/8 teaspoon)
.IP \[bu]
Honey (62.5mL, 1/4 cup)
.IP \[bu]
Onion Powder (2.5mL, 1/2 teaspoon)
.IP \[bu]
Garlic (3 cloves)
.IP \[bu]
Cornstarch (5mL, 1 teaspoon)
.IP \[bu]
Ginger (1/2-inch knob, grated)
.IP \[bu]
Rice (500mL, 2 cups, cooked basmati)

.SH INSTRUCTIONS
.nr step 1 1
.IP \n[step]
In a small dish, combine \fBsoy sauce\fR (45mL, 3 tablespoons), \fBsesame
oil\fR (15mL, 1 tablespoon), \fBrice vinegar\fR (10mL, 2 teaspoons), \fBred
pepper flakes\fR (0.625mL, 1/8 teaspoon), \fBhoney\fR (62.5mL, 1/4 cup),
\fBonion powder\fR (2.5mL, 1/2 teaspoon), \fBgarlic\fR (3 cloves, minced),
\fBcornstarch\fR (5mL, 1 teaspoon) and \fBginger\fR (1/2-inch knob,
grated). Set aside.
.IP \n+[step]
In a cast iron pan over high heat, add \fBvegetable oil\fR (15mL, 1
tablespoon). Add \fBtofu\fR (454g, 1 lb.) and sear on all sides until beginning
to brown.
.IP \n+[step]
Add soy sauce / honey mixture, reduce heat slightly, stir to coat the tofu and
cook until sauce has thickened.
.IP \n+[step]
Serve tofu over a bed of rice or with veggies.

.SH COMMENT
.IP \[bu]
Estimated Prep Time: 10m
.IP \[bu]
Estimated Cook Time: 20m
.IP \[bu]
Difficulty: easy

.SH ADDITIONAL NOTES
This dish is great served over a bed of rice with broccoli, or with roasted
asparagus and sweet potato. Serve with your side of choice.

