.TH recipe-manuals 7 "Maple Pecan Salmon" "" "Maple Pecan Salmon"

.SH NAME
Maple Pecan Salmon

.SH INGREDIENTS
.IP \[bu]
Salmon Filets (454g, 1 lb.)
.IP \[bu]
Maple Syrup (62mL, 1/4 cup)
.IP \[bu]
Soy Sauce (30mL, 2 tablespoons)
.IP \[bu]
Garlic (1 clove)
.IP \[bu]
Black Pepper (0.625mL, 1/8 teaspoon)
.IP \[bu]
Toasted Pecans (small handful)
.IP \[bu]
Asparagus (1 bunch)
.IP \[bu]
Baby Potatoes (908g, 2 lb.)

.SH INSTRUCTIONS
.nr step 1 1
.IP \n[step]
In a small bowl, mix \fBmaple syrup\fR (62mL, 1/4 cup), \fBsoy sauce\fR (30mL,
2 tablespoons), \fBgarlic\fR (1 clove, minced), \fBblack pepper\fR (0.625mL, 1/8
teaspoon).
.IP \n+[step]
Add \fBsalmon\fR (454g, 1 lb.) to mixture, and mix well. Cover and marinade in
fridge for 1 hour.
.IP \n+[step]
Place salmon in shallow baking dish and pour any remaining syrup mixture over
salmon. Coat with \fBtoasted pecans\fR (small handful, crushed).
.IP \n+[step]
In a separate baking dish, add \fBasparagus\fR (1 bunch) and \fBbaby
potatoes\fR (908g, 2 lb.). Coat in olive oil and salt as desired.
.IP \n+[step]
Preheat oven to 400°F / 204°C and bake salmon and vegetables for 20 minutes or
until cooked.

.SH COMMENT
.IP \[bu]
Estimated Prep Time: 1h (marinade salmon), 10m prep
.IP \[bu]
Estimated Cook Time: 20m
.IP \[bu]
Difficulty: easy

.SH ADDITIONAL NOTES
Substitute asparagus and baby potatoes with your veggies of choice (roasted
beets, for example), or serve with rice.

