.TH recipe-manuals 7 "Taco Seasoning" "" "Taco Seasoning"

.SH NAME
Taco Seasoning

.SH INGREDIENTS
.IP \[bu]
Chili Powder (15mL, 1 tablespoon)
.IP \[bu]
Ground Cumin (7.5mL, 1.5 teaspoons)
.IP \[bu]
Sea Salt (5mL, 1 teaspoon)
.IP \[bu]
Ground Black Pepper (5mL, 1 teaspoon)
.IP \[bu]
Ground Paprika (2.5mL, 0.5 teaspoon)
.IP \[bu]
Garlic Powder (1.25mL, 0.25 teaspoon)
.IP \[bu]
Onion Powder (1.25mL, 0.25 teaspoon)
.IP \[bu]
Crushed Red Pepper Flakes (1.25mL, 0.25 teaspoon)
.IP \[bu]
Dried Oregano (1.25mL, 0.25 teaspoon)

.SH INSTRUCTIONS
.nr step 1 1
.IP \n[step]
Combine all ingredients in a bowl.

.SH COMMENT
.IP \[bu]
Estimated Prep Time: 10 minutes
.IP \[bu]
Estimated Cook Time: none
.IP \[bu]
Difficulty: easy

.SH ADDITIONAL NOTES
This recipe yields about (30mL, 2 tablespoons) of mix.

